### ISSUE TITLE
dryRun = true - Results in strange errors

### ISSUE THREAD

**Issue by jerrywiltse** [bintray/gradle-bintray-plugin#115]
Windows 10, Gradle 2.10

Someone set dryrun=true in our build. The result was a very strange condition where the bintrayUpload task hangs indefinitely.  When i ran with --debug i saw that it was some infinite loop of some kind. 

Here is the stacktrace of the error that apparently precedes the loop: 

:bintray-core:generatePomFileForGroovyMavenPublication
:bintray-core:compileJava UP-TO-DATE
:bintray-core:compileGroovy UP-TO-DATE
:bintray-core:processResources UP-TO-DATE
:bintray-core:classes UP-TO-DATE
:bintray-core:jar UP-TO-DATE
:bintray-core:publishGroovyMavenPublicationToMavenLocal
:bintray-core:bintrayUpload:bintray-core:bintrayUpload: Could not find publication: shadow.

client disconnection detected, stopping the daemon
Unable to execute command Build{id=530c822d-dbb6-41ad-9b74-cdfe3a086b6b.1, currentDir=C:\MyProjects\myproject} from socket connection from /127.0.0.1:45100 to /127.0.0.1:45101. Dispatching the failure to the daemon client
org.gradle.messaging.remote.internal.MessageIOException: Could not write message Failure[value=org.gradle.launcher.daemon.server.api.DaemonStoppedException: Gradle build daemon has been stopped.] to '/127.0.0.1:45101'.
	at org.gradle.messaging.remote.internal.inet.SocketConnection.dispatch(SocketConnection.java:111)
	at org.gradle.launcher.daemon.server.SynchronizedDispatchConnection.dispatch(SynchronizedDispatchConnection.java:55)
	at org.gradle.launcher.daemon.server.DefaultDaemonConnection.completed(DefaultDaemonConnection.java:129)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy.doBuild(StartBuildOrRespondWithBusy.java:59)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ReturnResult.execute(ReturnResult.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.HandleCancel.execute(HandleCancel.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.api.HandleStop.execute(HandleStop.java:33)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.DefaultDaemonCommandExecuter.executeCommand(DefaultDaemonCommandExecuter.java:56)
	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.handleCommand(DefaultIncomingConnectionHandler.java:154)
	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.receiveAndHandleCommand(DefaultIncomingConnectionHandler.java:129)
	at org.gradle.launcher.daemon.server.DefaultIncomingConnectionHandler$ConnectionWorker.run(DefaultIncomingConnectionHandler.java:117)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.esotericsoftware.kryo.KryoException: java.io.IOException: An existing connection was forcibly closed by the remote host
	at com.esotericsoftware.kryo.io.Output.flush(Output.java:156)
	at com.esotericsoftware.kryo.io.Output.require(Output.java:134)
	at com.esotericsoftware.kryo.io.Output.writeBytes(Output.java:219)
	at org.gradle.internal.serialize.kryo.KryoBackedEncoder.writeBytes(KryoBackedEncoder.java:43)
	at org.gradle.internal.serialize.AbstractEncoder$EncoderStream.write(AbstractEncoder.java:72)
	at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877)
	at java.io.ObjectOutputStream$BlockDataOutputStream.flush(ObjectOutputStream.java:1822)
	at java.io.ObjectOutputStream.flush(ObjectOutputStream.java:719)
	at org.gradle.messaging.remote.internal.Message.send(Message.java:42)
	at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.write(BaseSerializerFactory.java:152)
	at org.gradle.internal.serialize.BaseSerializerFactory$ThrowableSerializer.write(BaseSerializerFactory.java:146)
	at org.gradle.launcher.daemon.protocol.DaemonMessageSerializer$FailureSerializer.write(DaemonMessageSerializer.java:66)
	at org.gradle.launcher.daemon.protocol.DaemonMessageSerializer$FailureSerializer.write(DaemonMessageSerializer.java:57)
	at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.write(DefaultSerializerRegistry.java:91)
	at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$2.write(Serializers.java:46)
	at org.gradle.messaging.remote.internal.KryoBackedMessageSerializer$1.write(KryoBackedMessageSerializer.java:55)
	at org.gradle.messaging.remote.internal.inet.SocketConnection.dispatch(SocketConnection.java:108)
	... 20 more
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
	at sun.nio.ch.SocketDispatcher.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:236)
	at org.gradle.messaging.remote.internal.inet.SocketConnection$SocketOutputStream.write(SocketConnection.java:223)
	at com.esotericsoftware.kryo.io.Output.flush(Output.java:154)
	... 36 more
Daemon vm is shutting down... The daemon has exited normally or was terminated in response to a user interrupt.

**Comment by eyalbe4** [comment]
Thanks for reporting this issue @jerrywiltse.
We identified and fixed the issue with [this commit](https://github.com/bintray/gradle-bintray-plugin/commit/dd71eaf2aaebf221cdda4f89a55d08730ac4c0a1). It will be included in the next release of the plugin.

**Comment by eyalbe4** [comment]
@jerrywiltse, version 1.7 includes this fix.
