### ISSUE TITLE
Automatic publishing fails if a previously uploaded version was deleted

### ISSUE THREAD

**Issue by PaleoCrafter** [bintray/gradle-bintray-plugin#140]
I'm currently working on automating builds for one of my projects and hence end up deleting some versions from Bintray if something about the added metadata isn't quite right yet etc. However, this seems to cause problems with the automatic publishing of artifacts for a version.

Whenever I run the `bintrayUpload` task I get the following error:
```
Could not publish '<package>/<deleted-version>': HTTP/1.1 404 Not Found [message:Version '<deleted-version>' was not found]
```

It seems like either the plugin keeps a cache somewhere locally and doesn't properly update it or that it doesn't get the correct information from the API, in which case that would require fixing.

I can temporarily disable automatic publishing to mitigate this issue, but a proper solution would be much appreciated.

**Comment by eyalbe4** [comment]
Thanks for reporting this @PaleoCrafter. We're checking this now.

**Comment by eyalbe4** [comment]
@PaleoCrafter, we tried replicating this issue by creating a version, publishing it, deleting it and then doing it all again. We couldn't see the issue you reported. We invoked Bintray's REST APIs directly, which is what the gradle plugin is doing behind the scene. The plugin has no cache of its own. We want to understand the case of the issue. Can you please send an email to support@jfrog.com with all the issue details, so that we can work with you and help you resolve it?

**Comment by PaleoCrafter** [comment]
It appears the issue is resolved now, I'm able to upload and auto-publish just fine. If I have problems again in the future, I will directly contact you. Thanks for your quick response!

**Comment by andreas-schilling** [comment]
I had the same issue and also one day later is disappeared. I guess it is hard to reproduce because I did some wild publish-delete cycles as my publishing config in gradle was buggy first.
The old versions I have seen also looked like a direct `toString()` of the version instances behind them. From the hashes I could see, that it were always the same old versions popping up.
If the plugin itself doesn't have a cache, maybe your backend has one of some kind? It looks like the old versions finally disappear after a certain period of time.
Another question: looking at the source I could see that the plugin retrieves all versions of a package and signs all of them. Why is it like that? Why doesn't it look up just the version that currently is being published? If it wouldn't try to sign all of them, the problem wouldn't appear as well.

**Comment by eyalbe4** [comment]
Hi @andreas-schilling,
Thanks for sharing this information. As for your question, the plugin allowa you to have your Gradle project publish sub module into different Bintray repositories, packages and versions. To do that, you simply configure them inside the bintray closures of the modules. To allow you to optionally publish and sign the versions, the plugin uses the last bintrayUpload task to do that (those operations must be performed only at the very end of the build). That's why the code saves all versions, and then publishes them.

**Comment by vlad20012** [comment]
I had the same issue. I'm using gradle daemon. And I have and idea.
You using static collectoin 'repositories' in BintrayUploadTask. It can outlive one build and then crashes next build if the version was deleted.

The stachtrace:
```
Caused by: org.gradle.api.GradleException: Could not publish '<USER>/maven/<REPO>/<VERSION>': HTTP/1.1 404 Not Found [message:Version '<VERSION>' was not found]
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure9$_closure41$_closure43.doCall(BintrayUploadTask.groovy:402)
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
	at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure9.doCall(BintrayUploadTask.groovy:395)
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure11.doCall(BintrayUploadTask.groovy:441)
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure11.doCall(BintrayUploadTask.groovy)
	at com.jfrog.bintray.gradle.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:464)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by eyalbe4** [comment]
@vlad20012, I think you found the issue. Thank you for this!
We are working on a fix.

**Comment by eyalbe4** [comment]
@vlad20012, we committed [this fix](https://github.com/bintray/gradle-bintray-plugin/commit/2af723484c76147c5f544c842fd0cbf8a5cdc9bf) and created a snapshot version with the fix. Please try it out and let us know if it resolves the issue (and thanks again for pinpointing the issue :))
Here's how you apply the snapshot version:

```
buildscript {
	repositories {
		maven {
			url 'https://oss.jfrog.org/oss-snapshot-local'
		}
		jcenter()
	}
	dependencies {
		classpath "com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8-SNAPSHOT"
	}
}

apply plugin: 'com.jfrog.bintray'
```

**Comment by vlad20012** [comment]
Yep, it's fixed now. Thanks for the quick response.
P.S. We often hear that non-primitive or mutable statics is evil. And indeed it is :)

**Comment by andreas-schilling** [comment]
Awesome work everyone!
So, 1.8 release is going to be available soonish? :-)

**Comment by eyalbe4** [comment]
Sure @andreas-schilling, we'll publish 1.8 soon and update here when it is available.

**Comment by eyalbe4** [comment]
Sure @andreas-schilling, we'll publish 1.7.2 soon and update here when it is available.

**Comment by eyalbe4** [comment]
@vlad20012,  @andreas-schilling and @PaleoCrafter,
Version 1.7.2 with this fix has been released.
