### ISSUE TITLE
Imcomplete error message

### ISSUE THREAD

**Issue by caipivara** [bintray/gradle-bintray-plugin#158]
Hi

After running `bintrayUpload` I get:

```Caused by: org.gradle.api.GradleException: Could not create package 'danielnull/maven/debug-artist': HTTP/1.1 400 Bad Request [message:No repository found under this GitHub path]
        at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5_closure22_closure26.doCall(BintrayUploadTask.groovy:281)
        at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
        at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
        at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5.doCall(BintrayUploadTask.groovy:264)
        at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5.doCall(BintrayUploadTask.groovy)
        at com.jfrog.bintray.gradle.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:459)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more
```

Which github repository? what url?

**Comment by SimonScholz** [comment]
I am facing the exact same issue right now.

https://github.com/SimonScholz/RxSWT

```simon@simons:~/git/RxSWT/RxSwt$ ../gradlew bU
> Task :RxSwt:bintrayUpload FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':RxSwt:bintrayUpload'.
> Could not create package 'simon-scholz/RxJava-Extensions/RxSwt': HTTP/1.1 400 Bad Request [message:No repository found under this GitHub path]

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

```

Please give a hint, where I do have to put this  GitHub path.
