### ISSUE TITLE
Better Error Handling

### ISSUE THREAD

**Issue by RobertFischer** [bintray/gradle-bintray-plugin#18]
I'm trying to upload my project to Bintray, and getting this error:

```
Caused by: groovyx.net.http.HttpResponseException: Method Not Allowed
    at groovyx.net.http.HTTPBuilder.defaultFailureHandler(HTTPBuilder.java:652)
    at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:508)
    at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:441)
    at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:373)
    at groovyx.net.http.HTTPBuilder$request.call(Unknown Source)
    at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure4.doCall(BintrayUploadTask.groovy:151)
    at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure4.doCall(BintrayUploadTask.groovy)
    at com.jfrog.bintray.gradle.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:192)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    ... 50 more
```

Looking at this line of code, it's not clear what the problem is:
https://github.com/bintray/gradle-bintray-plugin/blob/master/src/main/groovy/com/jfrog/bintray/gradle/BintrayUploadTask.groovy#L151

Is there any suggestion how to do identify what the problem is? If so, I'll add some improved error handling and submit an pull request.

**Comment by scanor** [comment]
我出现了相同的问题，而且我确定我的bintray账号密码并没有错

**Comment by eyalbe4** [comment]
@scanor, your last comment is not readable.
@RobertFischer, can you please share a sample project that reproduces this error? I'm not sure we can guess the cause of the problem without it.
Thanks.

**Comment by scanor** [comment]
@eyalbe4  I,m sorray about my poor English, I can read English ,but I can't write. My last comment mean that I am sure about my bintray account and password are right. But In some computer,I can upload success  while some can not.

**Comment by Omico** [comment]
I have the same problem, This is my project https://github.com/Omico/SetupWizardLib

**Comment by mmren** [comment]
我也遇到相同的问题

**Comment by mmren** [comment]
Caused by: groovyx.net.http.HttpResponseException: Method Not Allowed
        at groovyx.net.http.HTTPBuilder.defaultFailureHandler(HTTPBuilder.java:651)
        at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1070)
        at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:1044)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
        at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
        at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:366)
        at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
        at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5.doCall(BintrayUploadTask.groovy:249)
        at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure5.doCall(BintrayUploadTask.groovy)
        at com.jfrog.bintray.gradle.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:459)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        ... 77 more

**Comment by mmren** [comment]
12:45:41.926 [INFO] [org.gradle.api.Task] Gradle Bintray Plugin version: 1.8.0
12:45:41.930 [INFO] [com.jfrog.bintray.gradle.BintrayHttpClientFactory] Using proxy null:@mirrors.zzu.edu.cn:80
12:45:41.932 [DEBUG] [org.gradle.model.collection.internal.BridgedCollections] Ignoring element 'tasks' added to 'bintrayUpload' after it is closed.
12:45:41.935 [DEBUG] [groovyx.net.http.HTTPBuilder] HEAD https://api.bintray.com/packages/GPL_R/app_core/core
12:45:41.943 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {tls}->http://mirrors.zzu.edu.cn:80->https://api.bintray.com
12:45:42.514 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to mirrors.zzu.edu.cn:80
12:45:42.998 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
12:45:42.998 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
12:45:42.998 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: CONNECT api.bintray.com:443 HTTP/1.1
12:45:43.486 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 405 Method Not Allowed
12:45:43.486 [DEBUG] [org.apache.http.client.protocol.ResponseProcessCookies] Cookie spec not specified in HTTP context
12:45:43.486 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection 0.0.0.0:50575<->123.15.57.34:80 closed
12:45:43.486 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] CONNECT refused by proxy: HTTP/1.1 405 Method Not Allowed
12:45:43.486 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Releasing connection org.apache.http.impl.conn.ManagedClientConnectionImpl@2846e903
12:45:43.487 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Connection can be kept alive for 9223372036854775807 MILLISECONDS
12:45:43.487 [DEBUG] [groovyx.net.http.HTTPBuilder] Response code: 405; found handler: org.codehaus.groovy.runtime.MethodClosure@71c9890
12:45:43.489 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
12:45:43.489 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':core:bintrayUpload'
12:45:43.489 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] :core:bintrayUpload FAILED
