### ISSUE TITLE
Depending on 'publish_____PublicationToMavenLocal' instead of 'publishToMavenLocal' breaks plugin in Gradle 2.4+

### ISSUE THREAD

**Issue by stormbeta** [bintray/gradle-bintray-plugin#70]
The bintray plugin is broken on Gradle 2.4+, because the task that bintrayUpload is trying to depend on doesn't exist until after bintrayUpload tries to depend on it, throwing a NullPointerException. This isn't a bug in Gradle 2.4 as far as I understand; rather it's due to Gradle moving more tasks to the new model API.

1. Bintray configuration should depend on publication artifacts, not local install
2. If it must depend on local install, then it should use the main 'publishToMavenLocal' task. This could cause extra publications to get installed locally, but I don't see a clean way to handle this otherwise without breaking backwards compatibility.

**Comment by sparkym3** [comment]
When running against this plugin on 2.4 I am having this issue as well and would appreciate a fix.

**Comment by eyalbe4** [comment]
Thanks for reporting this issue. We are looking into this and will update soon.

**Comment by eyalbe4** [comment]
Version 1.2 of the gradle-bintray-plugin was released today.
It includes a fix for this issue.

**Comment by sparkym3** [comment]
I am still seeing an issue with the 1.2 version. Below is that stack trace and I am producing it by building this project after updating it to 1.2 of your plugin and gradle 2.4 https://github.com/etiennestuder/gradle-plugindev-plugin

$ gradlew assemble --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NullPointerException
        at org.gradle.api.internal.tasks.DefaultTaskDependency.add(DefaultTaskDependency.java:109)
        at org.gradle.api.internal.AbstractTask$11.run(AbstractTask.java:327)
        at org.gradle.api.internal.tasks.TaskMutator.mutate(TaskMutator.java:37)
        at org.gradle.api.internal.AbstractTask.dependsOn(AbstractTask.java:325)
        at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2_closure5.doCall(BintrayPlugin.groovy:91)
        at com.jfrog.bintray.gradle.BintrayPlugin$_apply_closure2.doCall(BintrayPlugin.groovy:83)
        at BuildAdapter1_groovyProxy.projectsEvaluated(Unknown Source)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.projectsEvaluated(Unknown Source)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.messaging.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
        at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:31)
        at org.gradle.messaging.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy11.projectsEvaluated(Unknown Source)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:132)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:90)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:50)
        at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:27)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:169)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:55)


BUILD FAILED

**Comment by stormbeta** [comment]
@sparkym3 I think the problem is caused because plugindevplugin's buildscript applies an older version of itself, which uses the older bintray plugin version. You'll probably need to include the newer version of the bintray plugin on your buildscript classpath to force it to use the newer version.

**Comment by sparkym3** [comment]
Yup, I noticed that it was an issue with the plugindevplugin build and tried to delete my comment before anyone replied. Since the plugin uses itself to build itself it required me to build against the old gradle with the new 1.2 and then build against that build with the new gradle.
