### ISSUE TITLE
Could not sign version ... HTTP/1.1 404 Not Found [message:Version ... was not found]

### ISSUE THREAD

**Issue by johnjohndoe** [bintray/gradle-bintray-plugin#92]
I am trying to add this plugin to a **Java library project** of mine. The Bintray project can be found here:
https://bintray.com/tbsprs/maven/HalfnarpClient

Please find the deployment configuration here:
[build.gradle](https://github.com/johnjohndoe/HalfnarpClient/blob/97c82152800236419b9e8773a95ca0c94d124674/build.gradle), [deploy.gradle](https://github.com/johnjohndoe/HalfnarpClient/blob/97c82152800236419b9e8773a95ca0c94d124674/ci/deploy.gradle), [gradle.properties](https://github.com/johnjohndoe/HalfnarpClient/blob/97c82152800236419b9e8773a95ca0c94d124674/gradle.properties)

I execute the following Gradle command:
``` bash
$ ./gradlew clean bintrayUpload
```

This **fails** with the following error message:
> Execution failed for task ':bintrayUpload'.
> \> Could not sign version 'v.2.0.0': HTTP/1.1 404 Not Found [message:Version 'v.2.0.0' was not found]

This is the stacktrace:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':bintrayUpload'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
...

Caused by: org.gradle.api.GradleException: Could not sign version 'v.2.0.0': HTTP/1.1 404 Not Found [message:Version 'v.2.0.0' was not found]
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure7_closure33_closure35.doCall(BintrayUploadTask.groovy:321)
	at groovyx.net.http.HTTPBuilder$1.handleResponse(HTTPBuilder.java:503)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:515)
	at groovyx.net.http.HTTPBuilder.doRequest(HTTPBuilder.java:434)
	at groovyx.net.http.HTTPBuilder.request(HTTPBuilder.java:383)
	at groovyx.net.http.HTTPBuilder$request$0.call(Unknown Source)
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure7.doCall(BintrayUploadTask.groovy:312)
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure11.doCall(BintrayUploadTask.groovy:403)
	at com.jfrog.bintray.gradle.BintrayUploadTask$_bintrayUpload_closure11.doCall(BintrayUploadTask.groovy)
	at com.jfrog.bintray.gradle.BintrayUploadTask.bintrayUpload(BintrayUploadTask.groovy:428)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
...
```

**Comment by johnjohndoe** [comment]
@yoav @eyalbe4 Any comment please?

**Comment by eyalbe4** [comment]
@johnjohndoe, thanks for reporting thjs. We're looking into this issue now. We will reply soon.

**Comment by eyalbe4** [comment]
Hi @johnjohndoe,
I tried replicating this issue by cloning your project and running the build (I did have to set the 'sighn' property to true though).
I didn't get the error and all files have been created and signed by Bintray:
```
/info/metadude/java/library/halfnarp/halfnarp-client/2.0.0
Name	Updated	Size	

-	-	
 halfnarp-client-2.0.0-sources.jar 	moments ago	9 KB	
Actions 
 halfnarp-client-2.0.0-sources.jar.asc 	moments ago	183 B	
Actions 
 halfnarp-client-2.0.0.jar 	moments ago	14.1 KB	
Actions 
 halfnarp-client-2.0.0.jar.asc 	moments ago	183 B	
Actions 
 halfnarp-client-2.0.0.pom 	moments ago	1.2 KB	
Actions 
 halfnarp-client-2.0.0.pom.asc 	moments ago	183 B	
Actions 
```

I noticed however that the error you got says "Could not sign version 'v.2.0.0", which is strange, because the files are created in version 2.0.0...
I can't think of a scenario that causes the plugin creates version A and then tries to sign version B, but we do want to understand how you achieved this scenario and for that we need to be able to reproduce it.
Can you please check again that the issue is reproduced with these sources? If not, can you please provide us with another sample? Another troubleshooting option might be that you try using the [gradle-bintray-plugin-examples](https://github.com/bintray/bintray-examples/tree/master/gradle-bintray-plugin-examples)
In any case, we are here to assist you.

**Comment by johnjohndoe** [comment]
I tried different settings for "Bintray logical version name" in `... version { name = project.versionName } ...` since [I used `v.1.0.0` for the initial release](https://bintray.com/tbsprs/maven/HalfnarpClient/v.1.0.0/view). As far as I understand a plain `1.0.0` is common on Bintray. I might have pasted the old error message.

**Comment by johnjohndoe** [comment]
I tried again today and it seems to be working. I will close the issue for now. Thank you.

**Comment by renatoathaydes** [comment]
I'm facing the same issue...

All files have the correct version I have in the build file, but when signing, it says it can't sign a different version...

Here's a partial output example:

```
Uploading to https://api.bintray.com/content/renatoathaydes/maven/automaton/1.3.2-beta/com/athaydes/automaton/Automaton/1.3.2-beta/Automaton-1.3.2-beta.pom...
Uploaded to 'https://api.bintray.com/content/renatoathaydes/maven/automaton/1.3.2-beta/com/athaydes/automaton/Automaton/1.3.2-beta/Automaton-1.3.2-beta.pom'.
:bintrayUpload FAILED
:bintrayUpload (Thread[Daemon worker Thread 4,5,main]) completed. Took 2 mins 7.712 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':bintrayUpload'.
> Could not sign version '1.3.1': HTTP/1.1 404 Not Found [message:Version '1.3.1' was not found]
```

As you can see, I uploaded version 1.3.2-beta, but the error message says the plugin tried to sign version 1.3.1.

Version 1.3.1 is the last commited version in Git. Seems like the signing task gets the version from the commited version, not the build file.

After I commited the build file, it worked.

**Comment by HongJun2046** [comment]
I'm facing the same issue...
i solve by kill java process

**Comment by xuuuu** [comment]
I'm facing the same issue when I upload new version after delete the previous version,
and how can I solve it?

**Comment by alinhayati** [comment]
Same issue for me too, after deleting the old version I still face the error ...

**Comment by micHar** [comment]
@HongJun2046 solution worked for me. Simply call `killall -9 java` from your terminal. Also for me it probably occured because I was experimenting with different repo names and bintray plugin must have cached something.
